language: go

go:
  - "1.10.1"

sudo: false

install:
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/golang/lint/golint
  - go get github.com/golang/dep/cmd/dep

script:
  - make vendor-status
  - make vet
  - make imports
  - make importscheck
  - make lintcheck
